class Object:
   # ActionScript3 Base object
   def __init__(self):...
   def hasOwnProperty(self, name: str):...
   def isPrototypeOf(self, theClass):...
   def propertyIsEnumerable(self, name: str):...
   def setPropertyIsEnumerable(self, name: str, isEnum=True):...
   def toLocaleString(self):...
   def toString(self):...

   def valueOf(self):
      return self
